### ISSUE TITLE
What about more than two predictors?

### ISSUE THREAD

**Issue by luca-scr** [grantmcdermott/parttree#1]
As stated in the subject, how can we deal with the case of more than two predictors?
BTW, very nice visualisation.

**Comment by grantmcdermott** [comment]
Thanks Luca. I've turned off support for >2 predictors, because these are 2D plots. Yes, you can plot the partitions between two predictors from a higher-dimensional set, but then you're getting a misleading impression of the conditional splits. Hope that helps.

**Comment by grantmcdermott** [comment]
PS. I should add that I view this package as mostly useful for pedagogical purposes. As in, "Look, this is how a decision tree carves up the data when we have two predictors." For visualizing higher-order trees, you'd be best served by plotting a regular dendogram-style plot. There's _some_ support for this in **ggplot2** (I might try to add better functionality with this package somewhere down the line), but the easiest way is just to use base graphics or, even better, **rpart.plot**: http://www.milbo.org/rpart-plot/

**Comment by luca-scr** [comment]
Thanks for the reply. I also use a two-predictor case with the implied 2D partition when I introduce decision trees. Clearly, a tree of binary splits is the common way to show the output of the algorithm. I was just wondering if you have come up with a solution for more than 2 predictors.
