### ISSUE TITLE
Hex sticker?

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/parttree#11]
Playing around with a tree split of [this image](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Japanese_Zelkova_bonsai_16%2C_30_April_2012.JPG/480px-Japanese_Zelkova_bonsai_16%2C_30_April_2012.JPG). Thought it might make a nice hex sticker:

![hex](https://user-images.githubusercontent.com/10285037/126108205-df14f0cf-8d44-49dd-ac83-6a1265702f0c.png)

But, too busy? 

Curious if @juliasilge @zeileis have any thoughts?

**Comment by juliasilge** [comment]
Love the concept!

If you plan to actually print them, I think some helpful context might be looking at the level of detail on [some of the RStudio hex stickers](https://github.com/rstudio/hex-stickers), many of which I have seen in person. For example, I have seen the [flexdashboard](https://github.com/rstudio/hex-stickers/blob/master/thumbs/flexdashboard.png) and the new [dplyr](https://github.com/rstudio/hex-stickers/blob/master/thumbs/dplyr.png) stickers, both of which look great but are probably at the upper threshold of detail that you can really absorb on a printed hex sticker. I'd probably try changing the model parameters so it is a bit simpler?

**Comment by grantmcdermott** [comment]
Thanks Julia! I don't plan to physically print these, but good points to bear in mind nonetheless. I'll take a look at a simpler implementation later today.

**Comment by zeileis** [comment]
I agree: Very nice idea! And I would also suggest to reduce the amount of detail in the display - even if you don't print it. I would expect that it should make the connection between the package and the hex image clearer.

P.S.: Maybe you can take some inspiration from Piet Mondrian and how his paintings of fall trees got increasingly abstract. <http://fineartinschool.blogspot.com/2015/10/mondrian-fall-trees.html>

**Comment by grantmcdermott** [comment]
> P.S.: Maybe you can take some inspiration from Piet Mondrian and how his paintings of fall trees got increasingly abstract. http://fineartinschool.blogspot.com/2015/10/mondrian-fall-trees.html

Oh, cool!
