### ISSUE TITLE
geom_parttree unable to handle negative values

### ISSUE THREAD

**Issue by pjgeens** [grantmcdermott/parttree#6]
In the case of negative values on the x and y axis, geom_parttree uses the absolute value resulting in a misdrawn plot.

library(parttree)
library(dplyr)
library(rpart)
iris <- iris %>%
  mutate(Petal.Length = -Petal.Length,
         Petal.Width = -Petal.Width)

iris_tree = rpart(Species ~ Petal.Length + Petal.Width, data=iris)

p = ggplot(data = iris, aes(x = Petal.Length, y = Petal.Width)) +
  geom_point(aes(col = Species)) + 
  geom_parttree(data = iris_tree, aes(fill = Species), alpha=0.1)

p
![imageout](https://user-images.githubusercontent.com/12471774/102223034-7b7a2480-3ee4-11eb-85d2-29d43479486a.png)

**Comment by grantmcdermott** [comment]
Good catch, thanks. 

I've got some pressing issues to clear off my plate before I can return to this, but I'll try to fix as soon as I can a chance.

**Comment by pjgeens** [comment]
changing this one line solved it for me.
_pd$split = as.numeric(gsub(".+[^[:alnum:]\\-\\.\\s]", "", pv))_	
changed to          
_pd$split <- as.numeric(gsub(".+<|.+<=|>|.+>=", "", pv))_

**Comment by grantmcdermott** [comment]
Oh, nice. Do you mind putting in a quick PR?

**Comment by grantmcdermott** [comment]
nvm: just realised it was probably easier for me to do on this end.

thanks again for the catch and the fix!
